import { Inter } from "next/font/google";
import "./globals.css";
import { DetailProvider } from './Steps/DetailContext';
import { loadCsvData } from './pages/api/fetchCsv';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }) {
  const csvData = loadCsvData();
  return (
    <html lang="en">
      <body className={inter.className}>
      <DetailProvider data={csvData}>
        {children}
        </DetailProvider>
        </body>
    </html>
  );
}